<a href="https://colab.research.google.com/github/ZaeemAkbarKhan786/MS_ProgrammingForAI/blob/main/FA24_RAI_019_(Lab_Quiz_02).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Name:** Zaeem Akbar Khan
# **Registration #:** FA24-RAI-019

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/content/reviews_dataset.csv')

In [3]:
data.columns

Index(['news', 'type'], dtype='object')

In [4]:
data.head()

                                                news      type
0  China had role in Yukos split-up\n \n China le...  business
1  Oil rebounds from weather effect\n \n Oil pric...  business
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business
3  $1m payoff for former Shell boss\n \n Shell is...  business
4  US bank in $515m SEC settlement\n \n Five Bank...  business

In [5]:
data

                                                   news      type
0     China had role in Yukos split-up\n \n China le...  business
1     Oil rebounds from weather effect\n \n Oil pric...  business
2     Indonesia 'declines debt freeze'\n \n Indonesi...  business
3     $1m payoff for former Shell boss\n \n Shell is...  business
4     US bank in $515m SEC settlement\n \n Five Bank...  business
...                                                 ...       ...
2220  Microsoft launches its own search\n \n Microso...      tech
2221  Warnings about junk mail deluge\n \n The amoun...      tech
2222  Microsoft gets the blogging bug\n \n Software ...      tech
2223  Gamers snap up new Sony PSP\n \n Gamers have b...      tech
2224  Apple laptop is 'greatest gadget'\n \n The App...      tech

[2225 rows x 2 columns]

In [6]:
data.describe

<bound method NDFrame.describe of                                                    news      type
0     China had role in Yukos split-up\n \n China le...  business
1     Oil rebounds from weather effect\n \n Oil pric...  business
2     Indonesia 'declines debt freeze'\n \n Indonesi...  business
3     $1m payoff for former Shell boss\n \n Shell is...  business
4     US bank in $515m SEC settlement\n \n Five Bank...  business
...                                                 ...       ...
2220  Microsoft launches its own search\n \n Microso...      tech
2221  Warnings about junk mail deluge\n \n The amoun...      tech
2222  Microsoft gets the blogging bug\n \n Software ...      tech
2223  Gamers snap up new Sony PSP\n \n Gamers have b...      tech
2224  Apple laptop is 'greatest gadget'\n \n The App...      tech

[2225 rows x 2 columns]>

# Removing Non Numerical

In [ ]:
import pandas as pd
import re

def drop_non_alphabets(text):

  words = text.split()
  filtered_words = [word for word in words if word.isalpha()]
  return ' '.join(filtered_words)

data['news'] = data['news'].apply(drop_non_alphabets)

# Removing Stopwords

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

def remove_stopwords(sentences):
  stop_words = set(stopwords.words('english'))
  filtered_sentences = []
  for sentence in sentences:
    words = sentence.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    filtered_sentence = " ".join(filtered_words)
    filtered_sentences.append(filtered_sentence)
  return filtered_sentences

data['news'] = data['news'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

# Tokenization

In [7]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [9]:
import nltk
nltk.download('punkt_tab')
data['news'] = data['news'].astype(str).apply(word_tokenize)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

# Lemmitiazation

In [10]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmitizer = WordNetLemmatizer()
def lemmitize_words(text):
    return " ".join([lemmitizer.lemmatize(word,pos='v') for word in text.split()])

[nltk_data] Downloading package wordnet to /root/nltk_data...

In [11]:
def lemmatize_sentences(sentences):
    lemmatized_sentences = []
    for sentence in sentences:
        lemmatized_sentence = " ".join([lemmitizer.lemmatize(word, pos='v') for word in sentence.split()])
        lemmatized_sentences.append(lemmatized_sentence)
    return lemmatized_sentences

data['news'] = data['news'].apply(lemmatize_sentences)

In [12]:
first_row_sentences = data['news'][0]
print(first_row_sentences[0])

China

In [17]:
from sklearn.preprocessing import LabelEncoder
X = data['news']
Y = data['type']
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

# Ngram 2

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)
X_train = [' '.join(tokens) for tokens in X_train]
X_test = [' '.join(tokens) for tokens in X_test]
cv = CountVectorizer(ngram_range=(2, 2))
X_train_n_gram = cv.fit_transform(X_train)
X_test_n_gram = cv.transform(X_test)

rf = RandomForestClassifier()


rf.fit(X_train_n_gram, y_train)


y_pred = rf.predict(X_test_n_gram)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8545780969479354
[[133   0   4   3   2]
 [ 11  60   1  21   1]
 [  3   0  83   8   1]
 [  1   0   0 121   0]
 [ 15   2   0   8  79]]

# Ngram 3

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)


X_train = [' '.join(tokens) for tokens in X_train]
X_test = [' '.join(tokens) for tokens in X_test]


cv = CountVectorizer(ngram_range=(3, 3))


X_train_n_gram = cv.fit_transform(X_train)


X_test_n_gram = cv.transform(X_test)

rf = RandomForestClassifier()
rf.fit(X_train_n_gram, y_train)
y_pred = rf.predict(X_test_n_gram)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.77737881508079
[[114   2   4  21   1]
 [ 13  57   0  23   1]
 [  6   0  73  14   2]
 [  1   0   0 121   0]
 [ 15   7   0  14  68]]

# Randomforest

In [23]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=150)
rf.fit(X_train_n_gram, y_train)
y_pred = rf.predict(X_test_n_gram)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7737881508078994